package Vista;

import Modelo.productos;
import Modelo.productosDao;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileOutputStream;
import javax.swing.JPanel;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.text.Document;



/**
 *
 * @author LENOVO T440p
 */
public class Menu extends JFrame {

    productos pro = new productos();
    productosDao proDao = new productosDao();
    DefaultTableModel tmp = new DefaultTableModel();

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setSize(1004, 585);
        this.setLocationRelativeTo(null);
        setResizable(false);
        this.setTitle("Sistema de Ventas");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    }

    public void ListarProductos() {

        //limpiar tabla
        DefaultTableModel modeloTabla = (DefaultTableModel) tablaProductos.getModel();
        modeloTabla.setRowCount(0);

        //obtener la lista  de productos desde la base de datos
        List<productos> listaProductos = proDao.listar();

        // Rellena la tabla con los datos de cada producto
        for (productos prod : listaProductos) {
            Object[] fila = new Object[4];

            fila[0] = prod.getCodigo();
            fila[1] = prod.getNombre();
            fila[2] = prod.getPrecio();
            fila[3] = prod.getCantidadProducto();
            modeloTabla.addRow(fila);

        }
        tablaProductos.setModel(modeloTabla);
    }
    
    


private void cargarProductoEnTabla(List<productos> productos) {
    DefaultTableModel model = (DefaultTableModel) tablaResultados.getModel();
    model.setRowCount(0); // Limpia la tabla
    for (productos prod : productos) {
        model.addRow(new Object[]{
            prod.getCodigo(),
            prod.getNombre(),
            prod.getCantidadProducto(),
            prod.getPrecio()
        });
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cabecera = new javax.swing.JPanel();
        Ferreteria = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        texto = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        btnUsuario = new javax.swing.JButton();
        btnproductos = new javax.swing.JButton();
        btnTransaccion = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnCerrarsesion = new javax.swing.JButton();
        TabbedPanesistema = new javax.swing.JTabbedPane();
        panelTransaccion = new javax.swing.JPanel();
        LnombrePF = new javax.swing.JLabel();
        Lcodigo = new javax.swing.JLabel();
        Lcantidad = new javax.swing.JLabel();
        Lprecio = new javax.swing.JLabel();
        Lstock = new javax.swing.JLabel();
        txtNombrePF = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaResultados = new javax.swing.JTable();
        bEleminar = new javax.swing.JButton();
        LtotalApagar = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtTotalPagar = new javax.swing.JTextField();
        bImprimir = new javax.swing.JButton();
        tituloFactura = new javax.swing.JLabel();
        btnBuscarPorCodigo = new javax.swing.JButton();
        btnBuscarPorNombre = new javax.swing.JButton();
        agregar = new javax.swing.JButton();
        PanelProductos = new javax.swing.JPanel();
        tituloProducto = new javax.swing.JLabel();
        bGuardar = new javax.swing.JButton();
        bActualizar = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        codigop = new javax.swing.JLabel();
        nombrep = new javax.swing.JLabel();
        cantidadp = new javax.swing.JLabel();
        preciop = new javax.swing.JLabel();
        txtNombreP = new javax.swing.JTextField();
        txtCodigop = new javax.swing.JTextField();
        txtCantidadp = new javax.swing.JTextField();
        txtPreciop = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        PanelUsuario = new javax.swing.JPanel();
        tituloUsuario = new javax.swing.JLabel();
        ScrollPaneUusario = new javax.swing.JScrollPane();
        tablaUsuario = new javax.swing.JTable();
        lNombre = new javax.swing.JLabel();
        txtNombree = new javax.swing.JTextField();
        lApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lUusario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lPassword = new javax.swing.JLabel();
        txtPaword = new javax.swing.JTextField();
        ActualizarBtn = new javax.swing.JButton();
        EliminarBtn = new javax.swing.JButton();
        panelReportes = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cabecera.setBackground(new java.awt.Color(0, 153, 102));

        Ferreteria.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 24)); // NOI18N
        Ferreteria.setText("Ferretería La Cima");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/grande.png"))); // NOI18N

        texto.setBackground(new java.awt.Color(255, 255, 255));
        texto.setFont(new java.awt.Font("Bernard MT Condensed", 0, 24)); // NOI18N
        texto.setForeground(new java.awt.Color(255, 255, 255));
        texto.setText("Sistema de ventas");

        javax.swing.GroupLayout cabeceraLayout = new javax.swing.GroupLayout(cabecera);
        cabecera.setLayout(cabeceraLayout);
        cabeceraLayout.setHorizontalGroup(
            cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cabeceraLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ferreteria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 598, Short.MAX_VALUE)
                .addComponent(texto)
                .addGap(39, 39, 39))
        );
        cabeceraLayout.setVerticalGroup(
            cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(texto)
                        .addComponent(Ferreteria))
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(cabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 60));

        Menu.setBackground(new java.awt.Color(0, 153, 102));

        btnUsuario.setBackground(new java.awt.Color(0, 153, 102));
        btnUsuario.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        btnUsuario.setForeground(new java.awt.Color(234, 253, 234));
        btnUsuario.setText("Usuario");
        btnUsuario.setBorder(null);
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });

        btnproductos.setBackground(new java.awt.Color(0, 153, 102));
        btnproductos.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        btnproductos.setForeground(new java.awt.Color(234, 253, 234));
        btnproductos.setText("Productos");
        btnproductos.setBorder(null);
        btnproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproductosActionPerformed(evt);
            }
        });

        btnTransaccion.setBackground(new java.awt.Color(0, 153, 102));
        btnTransaccion.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        btnTransaccion.setForeground(new java.awt.Color(234, 253, 234));
        btnTransaccion.setText("Transacción");
        btnTransaccion.setBorder(null);
        btnTransaccion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaccionActionPerformed(evt);
            }
        });

        btnReportes.setBackground(new java.awt.Color(0, 153, 102));
        btnReportes.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(234, 253, 234));
        btnReportes.setText("Reportes");
        btnReportes.setBorder(null);
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        btnCerrarsesion.setBackground(new java.awt.Color(2, 126, 85));
        btnCerrarsesion.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnCerrarsesion.setText("Cerrar Sesion");
        btnCerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarsesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnproductos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTransaccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnReportes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCerrarsesion, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
            .addComponent(btnUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(btnTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnproductos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(btnCerrarsesion)
                .addGap(53, 53, 53))
        );

        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 550));

        panelTransaccion.setPreferredSize(new java.awt.Dimension(740, 495));

        LnombrePF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LnombrePF.setText("Nombre producto:");

        Lcodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Lcodigo.setText("Código:");

        Lcantidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Lcantidad.setText("Cantidad");

        Lprecio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Lprecio.setText("Precio");

        Lstock.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Lstock.setText("Stock Disponible");

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantidadKeyPressed(evt);
            }
        });

        txtPrecio.setEditable(false);
        txtPrecio.setBackground(new java.awt.Color(255, 255, 255));

        tablaResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOMBRE", "STOCK", "PRECIO", "TOTAL"
            }
        ));
        tablaResultados.setPreferredSize(new java.awt.Dimension(375, 60));
        jScrollPane1.setViewportView(tablaResultados);
        if (tablaResultados.getColumnModel().getColumnCount() > 0) {
            tablaResultados.getColumnModel().getColumn(0).setPreferredWidth(20);
            tablaResultados.getColumnModel().getColumn(1).setPreferredWidth(80);
            tablaResultados.getColumnModel().getColumn(2).setPreferredWidth(20);
        }

        bEleminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bEleminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        bEleminar.setText("Eliminar producto");
        bEleminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEleminarActionPerformed(evt);
            }
        });

        LtotalApagar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LtotalApagar.setText("Total a pagar:");

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoKeyPressed(evt);
            }
        });

        txtTotalPagar.setBackground(new java.awt.Color(235, 255, 235));
        txtTotalPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalPagarActionPerformed(evt);
            }
        });

        bImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/print.png"))); // NOI18N

        tituloFactura.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        tituloFactura.setText("Facturación");

        btnBuscarPorCodigo.setBackground(new java.awt.Color(0, 153, 102));
        btnBuscarPorCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscarPorCodigo.setText("Buscar");
        btnBuscarPorCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPorCodigoActionPerformed(evt);
            }
        });

        btnBuscarPorNombre.setBackground(new java.awt.Color(0, 153, 102));
        btnBuscarPorNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscarPorNombre.setText("Buscar");
        btnBuscarPorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPorNombreActionPerformed(evt);
            }
        });

        agregar.setBackground(new java.awt.Color(0, 204, 102));
        agregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        agregar.setForeground(new java.awt.Color(255, 255, 255));
        agregar.setText("Agregar Producto");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTransaccionLayout = new javax.swing.GroupLayout(panelTransaccion);
        panelTransaccion.setLayout(panelTransaccionLayout);
        panelTransaccionLayout.setHorizontalGroup(
            panelTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransaccionLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(panelTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransaccionLayout.createSequentialGroup()
                        .addGroup(panelTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTransaccionLayout.createSequentialGroup()
                                .addComponent(Lcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(Lprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelTransaccionLayout.createSequentialGroup()
                                .addComponent(LnombrePF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNombrePF, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarPorNombre)))
                        .addGap(29, 29, 29)
                        .addGroup(panelTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTransaccionLayout.createSequentialGroup()
                                .addComponent(Lcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscarPorCodigo))
                            .addGroup(panelTransaccionLayout.createSequentialGroup()
                                .addComponent(Lstock)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addGroup(panelTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bEleminar))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelTransaccionLayout.createSequentialGroup()
                        .addGroup(panelTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panelTransaccionLayout.createSequentialGroup()
                                .addComponent(bImprimir)
                                .addGap(18, 18, 18)
                                .addComponent(LtotalApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelTransaccionLayout.createSequentialGroup()
                                    .addGap(339, 339, 339)
                                    .addComponent(tituloFactura))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 27, Short.MAX_VALUE))))
        );
        panelTransaccionLayout.setVerticalGroup(
            panelTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransaccionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloFactura)
                .addGap(25, 25, 25)
                .addGroup(panelTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombrePF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LnombrePF)
                    .addComponent(btnBuscarPorNombre)
                    .addComponent(Lcodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPorCodigo)
                    .addComponent(bEleminar))
                .addGap(22, 22, 22)
                .addGroup(panelTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lcantidad)
                    .addComponent(Lprecio)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lstock)
                    .addComponent(agregar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransaccionLayout.createSequentialGroup()
                        .addGroup(panelTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LtotalApagar))
                        .addGap(13, 13, 13)))
                .addContainerGap())
        );

        TabbedPanesistema.addTab("TRANSACCION", panelTransaccion);

        tituloProducto.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        tituloProducto.setText("Productos");

        bGuardar.setBackground(new java.awt.Color(238, 253, 238));
        bGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/GuardarTodo.png"))); // NOI18N
        bGuardar.setText("REGISTRAR");
        bGuardar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 102), null));
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        bActualizar.setBackground(new java.awt.Color(238, 253, 238));
        bActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Actualizar (2).png"))); // NOI18N
        bActualizar.setText("ACTUALIZAR");
        bActualizar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 102), null));
        bActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActualizarActionPerformed(evt);
            }
        });

        bEliminar.setBackground(new java.awt.Color(238, 253, 238));
        bEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        bEliminar.setText("ELIMINAR");
        bEliminar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 102), null));
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        codigop.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        codigop.setText("Código:");

        nombrep.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        nombrep.setText("Nombre:");

        cantidadp.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        cantidadp.setText("Cantidad:");

        preciop.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        preciop.setText("Precio:");

        txtNombreP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePActionPerformed(evt);
            }
        });

        txtCantidadp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadpActionPerformed(evt);
            }
        });

        txtPreciop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPreciopActionPerformed(evt);
            }
        });

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOMBRE", "PRECIO", "STOCK"
            }
        ));
        tablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaProductos);
        if (tablaProductos.getColumnModel().getColumnCount() > 0) {
            tablaProductos.getColumnModel().getColumn(0).setPreferredWidth(45);
            tablaProductos.getColumnModel().getColumn(2).setPreferredWidth(40);
        }

        javax.swing.GroupLayout PanelProductosLayout = new javax.swing.GroupLayout(PanelProductos);
        PanelProductos.setLayout(PanelProductosLayout);
        PanelProductosLayout.setHorizontalGroup(
            PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProductosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelProductosLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(cantidadp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidadp, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelProductosLayout.createSequentialGroup()
                        .addGroup(PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombrep)
                            .addComponent(codigop, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(preciop, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelProductosLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodigop, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelProductosLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(txtPreciop, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(PanelProductosLayout.createSequentialGroup()
                .addGroup(PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelProductosLayout.createSequentialGroup()
                        .addGap(386, 386, 386)
                        .addComponent(tituloProducto))
                    .addGroup(PanelProductosLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelProductosLayout.setVerticalGroup(
            PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelProductosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(tituloProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelProductosLayout.createSequentialGroup()
                        .addGroup(PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codigop)
                            .addComponent(txtCodigop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombrep)
                            .addComponent(txtNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(preciop)
                            .addComponent(txtPreciop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(PanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cantidadp)
                            .addComponent(txtCantidadp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(bGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(bEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bActualizar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        TabbedPanesistema.addTab("PRODUCTOS", PanelProductos);

        tituloUsuario.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        tituloUsuario.setText("Gestionar Usuario");

        tablaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NOMBRE", "APELLIDO", "USUARIO", "PASSWORD"
            }
        ));
        ScrollPaneUusario.setViewportView(tablaUsuario);

        lNombre.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        lNombre.setText("Nombre:");

        lApellido.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        lApellido.setText("Apellido:");

        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });

        lUusario.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        lUusario.setText("Usuario:");

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        lPassword.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        lPassword.setText("Password:");

        txtPaword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPawordActionPerformed(evt);
            }
        });

        ActualizarBtn.setBackground(new java.awt.Color(0, 0, 255));
        ActualizarBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ActualizarBtn.setForeground(new java.awt.Color(255, 255, 255));
        ActualizarBtn.setText("Actualizar");
        ActualizarBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 153), null));

        EliminarBtn.setBackground(new java.awt.Color(255, 0, 0));
        EliminarBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EliminarBtn.setForeground(new java.awt.Color(255, 255, 255));
        EliminarBtn.setText("Eliminar");
        EliminarBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 0, 0), null));

        javax.swing.GroupLayout PanelUsuarioLayout = new javax.swing.GroupLayout(PanelUsuario);
        PanelUsuario.setLayout(PanelUsuarioLayout);
        PanelUsuarioLayout.setHorizontalGroup(
            PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUsuarioLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelUsuarioLayout.createSequentialGroup()
                        .addComponent(ScrollPaneUusario, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelUsuarioLayout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(tituloUsuario)
                        .addContainerGap(349, Short.MAX_VALUE))
                    .addGroup(PanelUsuarioLayout.createSequentialGroup()
                        .addGroup(PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelUsuarioLayout.createSequentialGroup()
                                .addComponent(lNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombree, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelUsuarioLayout.createSequentialGroup()
                                .addComponent(lApellido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(60, 60, 60)
                        .addGroup(PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelUsuarioLayout.createSequentialGroup()
                                .addComponent(lUusario, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelUsuarioLayout.createSequentialGroup()
                                .addComponent(lPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPaword, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ActualizarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EliminarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(130, 130, 130))))
        );
        PanelUsuarioLayout.setVerticalGroup(
            PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUsuarioLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(tituloUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPaneUusario, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNombre)
                    .addComponent(txtNombree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lUusario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ActualizarBtn))
                .addGap(18, 18, 18)
                .addGroup(PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lApellido)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPassword)
                    .addComponent(txtPaword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EliminarBtn))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        TabbedPanesistema.addTab("USUARIO", PanelUsuario);

        javax.swing.GroupLayout panelReportesLayout = new javax.swing.GroupLayout(panelReportes);
        panelReportes.setLayout(panelReportesLayout);
        panelReportesLayout.setHorizontalGroup(
            panelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );
        panelReportesLayout.setVerticalGroup(
            panelReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );

        TabbedPanesistema.addTab("REPORTES", panelReportes);

        getContentPane().add(TabbedPanesistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 870, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void menuActionPerformed(java.awt.event.ActionEvent evt) {

        }
    private void btnproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproductosActionPerformed

        ListarProductos();
        TabbedPanesistema.setSelectedIndex(1);

    }//GEN-LAST:event_btnproductosActionPerformed

    private void btnCerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarsesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarsesionActionPerformed

    
    private void btnTransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaccionActionPerformed
        TabbedPanesistema.setSelectedIndex(0);
    }//GEN-LAST:event_btnTransaccionActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        TabbedPanesistema.setSelectedIndex(2);
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        TabbedPanesistema.setSelectedIndex(3);
    }//GEN-LAST:event_btnReportesActionPerformed

    private void txtPawordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPawordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPawordActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void tablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosMouseClicked
        int fila = tablaProductos.rowAtPoint(evt.getPoint());
        txtCodigop.setText(tablaProductos.getValueAt(fila, 0).toString());
        txtNombreP.setText(tablaProductos.getValueAt(fila, 1).toString());
        txtPreciop.setText(tablaProductos.getValueAt(fila, 2).toString());
        txtCantidadp.setText(tablaProductos.getValueAt(fila, 3).toString());

    }//GEN-LAST:event_tablaProductosMouseClicked

    private void txtPreciopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPreciopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPreciopActionPerformed

    private void txtCantidadpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadpActionPerformed

    private void txtNombrePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed

        int filaSeleccionada = tablaProductos.getSelectedRow();
        if (filaSeleccionada >= 0) {
            String codigo = (String) tablaProductos.getValueAt(filaSeleccionada, 0);
            int respuesta = JOptionPane.showConfirmDialog(null, "¿Estás seguro de eliminar este producto?", "Eliminar", JOptionPane.YES_NO_OPTION);

            if (respuesta == JOptionPane.YES_OPTION) {

                if (proDao.EliminarProductos(codigo)) {
                    JOptionPane.showMessageDialog(null, "Producto eliminado correctamente");
                    ListarProductos();
                } else {
                    JOptionPane.showMessageDialog(null, "Error al eliminar el producto");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un producto para eliminar");
        }

    }//GEN-LAST:event_bEliminarActionPerformed

    private void bActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActualizarActionPerformed

        int filaSeleccionada = tablaProductos.getSelectedRow();
        if (filaSeleccionada >= 0) {
            String codigo = (String) tablaProductos.getValueAt(filaSeleccionada, 0);
            String nombre = txtNombreP.getText();

            // Validación del precio
            double precio;
            try {
                NumberFormat format = NumberFormat.getInstance(Locale.getDefault());
                Number number = format.parse(txtPreciop.getText().trim());
                precio = number.doubleValue();
            } catch (ParseException e) {
                JOptionPane.showMessageDialog(null, "Ingrese un valor numérico válido para el precio.");
                return;
            }

            // Validación de la cantidad
            int cantidad;
            try {
                cantidad = Integer.parseInt(txtCantidadp .getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese un valor numérico válido para la cantidad.");
                return;
            }

            // Crear el objeto producto y realizar la actualización
            productos productoActualizado = new productos(codigo, nombre, precio, cantidad);

            if (proDao.actualizarProducto(productoActualizado)) {
                JOptionPane.showMessageDialog(null, "Producto actualizado correctamente");
                ListarProductos();
            } else {
                JOptionPane.showMessageDialog(null, "Error al actualizar el producto");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un producto para actualizar");
        }
        //        if (proDao.actualizarProducto(productoActualizado)) {
            //    JOptionPane.showMessageDialog(null, "Producto actualizado correctamente");
            //    ListarProductos(); // Recarga la tabla
            //     }
    }//GEN-LAST:event_bActualizarActionPerformed

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        if (!"".equals(txtCodigop.getText()) || !"".equals(txtNombreP.getText()) || !"".equals(txtPreciop.getText()) || !"".equals(txtCantidadp.getText())) {
            pro.setCodigo(txtCodigop.getText());
            pro.setNombre(txtNombreP.getText());
            pro.setPrecio(Double.parseDouble(txtPreciop.getText()));
            pro.setCantidadProducto(Integer.parseInt(txtCantidadp.getText()));
            proDao.RegistrarProductod(pro);
            JOptionPane.showMessageDialog(null, "Producto registrado");
            ListarProductos();
        } else {
            JOptionPane.showMessageDialog(null, "Los campos estan vacios");
        }
    }//GEN-LAST:event_bGuardarActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        {
            if (!"".equals(txtCantidad.getText())) {
                String codigo = txtCodigo.getText();
                String nombre = txtNombrePF.getText();
                int cant = Integer.parseInt(txtCantidad.getText());
                double precio = Double.parseDouble(txtPrecio.getText());
                double total = cant * precio;
                int stock = Integer.parseInt(txtStock.getText());

                if (stock >= cant) {
                    // Inicializar el contador de items
                    int item = 0;
                    item++; // Incrementar el contador

                    tmp = (DefaultTableModel) tablaResultados.getModel();

                    // Verificar si el producto ya está registrado
                    for (int i = 0; i < tablaResultados.getRowCount(); i++) {
                        if (tablaResultados.getValueAt(i, 1).equals(txtNombrePF.getText())) {
                            JOptionPane.showMessageDialog(null, "El producto ya esta registrado");
                            return;
                        }
                    }

                    // Agregar producto a la tabla
                    Object[] O = new Object[5];
                    O[0] = codigo;
                    O[1] = nombre;        // Nombre
                    O[2] = cant;          // Cantidad
                    O[3] = precio;        // Precio
                    O[4] = total;         // Total

                    tmp.addRow(O);
                    tablaResultados.setModel(tmp);

                    // Actualizar total y limpiar campos
                    TotalPagar();
                    LimpiarVenta();
                    txtCodigo.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(null, "Stock no disponible");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese Cantidad");
            }
        }
    }//GEN-LAST:event_agregarActionPerformed

    private void btnBuscarPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPorNombreActionPerformed
        if (!"".equals(txtNombrePF.getText())) {
            String nombre = txtNombrePF.getText();
            productos pro = proDao.buscarProductoPorNombre(nombre);

            if (pro != null) {
                txtCodigo.setText(pro.getCodigo());
                txtPrecio.setText(String.valueOf(pro.getPrecio()));
                txtStock.setText(String.valueOf(pro.getCantidadProducto()));
                txtCantidad.requestFocus();
            } else {
                LimpiarVenta();
                JOptionPane.showMessageDialog(null, "Producto no encontrado");
                txtNombrePF.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese el nombre del producto");
            txtNombrePF.requestFocus();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarPorNombreActionPerformed

    private void btnBuscarPorCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPorCodigoActionPerformed

        if (!"".equals(txtCodigo.getText())) {
            String cod = txtCodigo.getText();
            pro = proDao.buscarPorCodigo(cod);
            if (pro.getNombre() != null) {
                txtNombrePF.setText("" + pro.getNombre());
                txtPrecio.setText("" + pro.getPrecio());
                txtStock.setText("" + pro.getCantidadProducto());
                txtCantidad.requestFocus();
            } else {
                LimpiarVenta();
                txtCodigo.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese el codigo del productos");
            txtCodigo.requestFocus();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarPorCodigoActionPerformed

    private void txtTotalPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalPagarActionPerformed
        TotalPagar();
    }//GEN-LAST:event_txtTotalPagarActionPerformed

    private void txtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyPressed

    }//GEN-LAST:event_txtCodigoKeyPressed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void bEleminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEleminarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tablaResultados.getModel();
        modelo.removeRow(tablaResultados.getSelectedRow());
        txtCodigo.requestFocus();
    }//GEN-LAST:event_bEleminarActionPerformed

    private void txtCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!"".equals(txtCantidad.getText())) {
                String codigo = txtCodigo.getText();
                String nombre = txtNombrePF.getText();
                int cant = Integer.parseInt(txtCantidad.getText());
                double precio = Double.parseDouble(txtPrecio.getText());
                double total = cant * precio;
                int stock = Integer.parseInt(txtStock.getText());

                if (stock >= cant) {
                    // Inicializar el contador de items
                    int item = 0;
                    item++; // Incrementar el contador

                    tmp = (DefaultTableModel) tablaResultados.getModel();

                    // Verificar si el producto ya está registrado
                    for (int i = 0; i < tablaResultados.getRowCount(); i++) {
                        if (tablaResultados.getValueAt(i, 1).equals(txtNombrePF.getText())) {
                            JOptionPane.showMessageDialog(null, "El producto ya esta registrado");
                            return;
                        }
                    }

                    // Agregar producto a la tabla
                    Object[] O = new Object[5];
                    O[0] = codigo;
                    O[1] = nombre;        // Nombre
                    O[2] = cant;          // Cantidad
                    O[3] = precio;        // Precio
                    O[4] = total;         // Total

                    tmp.addRow(O);
                    tablaResultados.setModel(tmp);

                    // Actualizar total y limpiar campos
                    TotalPagar();
                    LimpiarVenta();
                    txtCodigo.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(null, "Stock no disponible");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese Cantidad");
            }
        }
    }//GEN-LAST:event_txtCantidadKeyPressed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(Menuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(Menuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(Menuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(Menuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new Menu().setVisible(true);
                }
            });
        }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarBtn;
    private javax.swing.JButton EliminarBtn;
    private javax.swing.JLabel Ferreteria;
    private javax.swing.JLabel Lcantidad;
    private javax.swing.JLabel Lcodigo;
    private javax.swing.JLabel LnombrePF;
    private javax.swing.JLabel Lprecio;
    private javax.swing.JLabel Lstock;
    private javax.swing.JLabel LtotalApagar;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel PanelProductos;
    private javax.swing.JPanel PanelUsuario;
    private javax.swing.JScrollPane ScrollPaneUusario;
    private javax.swing.JTabbedPane TabbedPanesistema;
    private javax.swing.JButton agregar;
    private javax.swing.JButton bActualizar;
    private javax.swing.JButton bEleminar;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bGuardar;
    private javax.swing.JButton bImprimir;
    private javax.swing.JButton btnBuscarPorCodigo;
    private javax.swing.JButton btnBuscarPorNombre;
    private javax.swing.JButton btnCerrarsesion;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnTransaccion;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JButton btnproductos;
    private javax.swing.JPanel cabecera;
    private javax.swing.JLabel cantidadp;
    private javax.swing.JLabel codigop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lApellido;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lPassword;
    private javax.swing.JLabel lUusario;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel nombrep;
    private javax.swing.JPanel panelReportes;
    private javax.swing.JPanel panelTransaccion;
    private javax.swing.JLabel preciop;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTable tablaResultados;
    private javax.swing.JTable tablaUsuario;
    private javax.swing.JLabel texto;
    private javax.swing.JLabel tituloFactura;
    private javax.swing.JLabel tituloProducto;
    private javax.swing.JLabel tituloUsuario;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCantidadp;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigop;
    private javax.swing.JTextField txtNombreP;
    private javax.swing.JTextField txtNombrePF;
    private javax.swing.JTextField txtNombree;
    private javax.swing.JTextField txtPaword;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPreciop;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtTotalPagar;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

//    static class FrmMenu {
//
//        public FrmMenu() {
//        }
//
//        void setVisible(boolean b) {
//            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//        }
//    }
    private void LimpiarProductos() {

        txtCodigop.setText("");
        txtNombreP.setText("");
        txtPreciop.setText("");
        txtCantidadp.setText("");
    }
    
    private void TotalPagar() {
        double Totalpagar = 0.00;
        int numFila = tablaResultados.getRowCount();
        for (int i = 0; i < numFila; i++) {
            double cal = Double.parseDouble(String.valueOf(tablaResultados.getModel().getValueAt(i, 4)));
            Totalpagar = Totalpagar + cal;
        }
        txtTotalPagar.setText(String.format("%.2f", Totalpagar));
    }
    
    
    
    private void LimpiarVenta() {
        txtCodigo.setText("");
        txtNombrePF.setText("");
        txtCantidad.setText("");
        txtStock.setText("");
        txtPrecio.setText("");
    }
}
